#!/bin/bash

# Replace these with your actual deployed addresses from forge output
USDT_ADDRESS="PUT_USDT_ADDRESS_HERE"
ORACLE_ADDRESS="PUT_ORACLE_ADDRESS_HERE"
POOL_ADDRESS="PUT_POOL_ADDRESS_HERE"
POLICY_MANAGER_ADDRESS="PUT_POLICY_MANAGER_ADDRESS_HERE"

# Update .env.local
cat > /mnt/d/hackathoon/luminaa/lumina/.env.local << EOF
# Contract Addresses (BSC Testnet)
NEXT_PUBLIC_PREDICTION_MARKET_ADDRESS=0x0000000000000000000000000000000000000000
NEXT_PUBLIC_POOL_ADDRESS=${POOL_ADDRESS}
NEXT_PUBLIC_POLICY_MANAGER_ADDRESS=${POLICY_MANAGER_ADDRESS}
NEXT_PUBLIC_ORACLE_ADDRESS=${ORACLE_ADDRESS}
NEXT_PUBLIC_ASSET_TOKEN=${USDT_ADDRESS}

# API Keys
NEXT_PUBLIC_POLYMARKET_API_URL=https://clob.polymarket.com
NEXT_PUBLIC_GEMINI_API_KEY=AIzaSyB3a4DW7bV2IBYOeZhmqG96r3tzcUY
COHERE_API_KEY=gm5yjWj1N47K8a
EOF

echo "✅ Frontend .env.local updated!"
